CREATE TABLE IF NOT EXISTS subs(
    id SERIAL PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    get_updates BOOL NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);